apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obcs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kiranmohite2417/Online-Birth-Certificate-System-PHP.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: obcs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

